### ISSUE TITLE
ESP8266 support?

### ISSUE THREAD

**Issue by spotlesscoder** [sparky650/MCP23017#3]
Does this library work with the ESP8266? In particular, the NodeMCU 1.0 (ESP-12E)

**Comment by sparky650** [comment]
It does support ESP8266 using the Arduino framework either using the default i2c pins or specific pins. This can be used to initialize the chip with other pins: mcp.begin(0x20, SDA_PIN, SCL_PIN); Replace 0x20 with the address of your chip and the pins with your pins, keep in mind that not all of the ESP pins work for i2c and that Arduino uses different pin numbers from what is printed on the NodeMCU boards.
